"use strict";
// Shared by every Timofey homework set
const SPEAKING=[{"title":"Technology in my life","questions":["What technology do you use every day, and what could you not live without?","How did you first get interested in computers?","Do you think people spend too much time on their phones? Why or why not?","What was the last app or program you learned to use, and how did you learn it?","If you could invent a new gadget, what would it do?","What advice would you give to a grandparent who wants to start using the internet?"]},{"title":"Learning to code","questions":["Have you ever written a program or built a website? Tell me about it.","Which school subjects help you most with programming, and why?","Why do you think some teenagers find coding difficult?","Would you rather work for a big company or start your own IT business? Why?","How important is English for people who work with computers?","What would you say to a friend who wants to learn programming but doesn't know where to begin?"]},{"title":"Games and the internet","questions":["What kinds of video games do you enjoy, and what do you like about them?","Do you think computer games can be useful for learning? Explain.","How do you stay safe online?","Is it better to make friends online or in real life? Why?","Tell me about a time when the internet helped you solve a problem.","Should parents limit how long teenagers play games? What do you think?"]},{"title":"The future of technology","questions":["How do you think artificial intelligence will change school in the next ten years?","Which jobs might disappear because of robots, and which new jobs may appear?","Would you like to live in a fully smart home? Why or why not?","What is the biggest advantage and the biggest danger of modern technology?","How might your own life look in 2040?","What would you do if you had one day without any electronic devices?"]}];
function wordsIn(v){return (String(v||"").match(/[\p{L}\p{N}]+(?:['’\-][\p{L}\p{N}]+)*/gu)||[]).length;}
function norm(s){return String(s||"").toLowerCase().replace(/[’`]/g,"'").replace(/\s+/g," ").trim();}
function checkAnswer(id,answer){
  const key=KEYS[id];if(key===undefined)return null;
  const a=norm(answer);if(!a)return false;
  return key.split("|").some(k=>norm(k)===a||(k.startsWith("'")&&a.endsWith(norm(k))));
}
