"use strict";
// Answer keys for the OGE set (teacher page only). Accepted variants are separated by "|".
const KEYS={
"m1": "Coding instead of the beach",
"m2": "Why a simple password is a problem",
"m3": "Technology that describes the world",
"m4": "Learning history by playing",
"m5": "A faster way to charge",
"m6": "Screens and a good night's sleep",
"m7": "Giving old devices a second life",
"r1": "False",
"r2": "True",
"r3": "True",
"r4": "False",
"r5": "True",
"r6": "Not stated",
"r7": "Not stated",
"g1": "had had",
"g2": "has been bought",
"g3": "had finished",
"g4": "most useful",
"g5": "knew",
"g6": "were downloading",
"f1": "safety",
"f2": "revolutionary",
"f3": "relieved",
"f4": "ability",
"f5": "impossible",
"f6": "development",
"f7": "valuable"
};
